### ISSUE TITLE
API returns an empty list after calling download

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/GISAIDR#1]
When you call `download(...)` the second time the API returns an empty list in the responses. You can fix this by logging in again after each download.

**Comment by Wytamma** [comment]
Hey @AmyMikhail are you able to download sequences if you call `login()` again? That's a temporary fix for me... if you can only get 50 samples then that a problem!

**Comment by Wytamma** [comment]
I've recently add support for the EpiRSV database (set database="EpiRSV") in the login function. While doing this I think I figured out the solution to this download problem. Multiple download calls work for EpiRSV because the download pid and wid are loaded dynamically. In EpiCoV the pid and wid are only loaded at login and they change with every download attempt. 

# Fix 
Update GISAID to use the same download panel for EpiCoV as EpiRSV.

**Comment by AmyMikhail** [comment]
> Hey @AmyMikhail are you able to download all sequences if you call `login()` again? That's a temporary fix for me... if you can only get 50 samples then that's a problem!

Hi @Wytamma yes unfortunately even after logging in again it is still only giving me 50 results, likely because of the issue you raise above.  I'm happy to try it again once you apply the fix.

**Comment by Wytamma** [comment]
@AmyMikhail that actually seems like a different issue. I’m able to download 1000s of sequences using the download function. Albeit I have to call login() before each download(). The trace back with the query command above looks unrelated (query() isn’t called in download). GISAIDR doesn’t page through results it just loads all the entries you request at once so I’m not sure why download only returns 50? Maybe it’s an error with extracting the seqs from the .tar file? 

Can you try reinstalling turning debug on and pasting the output for download()?

**Comment by Wytamma** [comment]
> I've recently added support for the EpiRSV database (set database="EpiRSV") in the login function. While doing this I think I figured out the solution to this download problem. Multiple download calls work for EpiRSV because the download pid and wid are loaded dynamically. In EpiCoV the pid and wid are only loaded once at login and they change with every download attempt.
> 
> ## Fix
> Update GISAIDR to use the same download panel for EpiCoV as EpiRSV.

I implement this in [c90e4fd](https://github.com/Wytamma/GISAIDR/commit/c90e4fd98f304371ebb5fea5be31d0e14ebfba0b) which solved the problem.

**Comment by EliasReutelsterz** [comment]
Hi there! @Wytamma Is the package still active and should be working fine right now?
I just downloaded the latest version, typed in my credentials and get

Warning message:
In parseResponse(response) :
  There was an error please see: https://github.com/Wytamma/GISAIDR/issues/1
<simpleError in parseResponse(response): Error! Please login again.>

Is the error on my side?

**Comment by ammaraziz** [comment]
It appears GISAID has changed the end points, again. 

Unfortunately it's a game of cat and mouse.

**Comment by Temuge08** [comment]
Hello, it's very unfortunate that this happens when I really needed the access. Is there any workaround or solution?
