### ISSUE TITLE
gisaid fasta downloader tryCatch error

### ISSUE THREAD

**Issue by gk7279** [Wytamma/GISAIDR#10]
`> full_df_with_seq <- download(credentials = credentials,list_of_accession_ids=list_of_accession_ids,get_sequence=TRUE)`

`Compressing data. Please wait...
Data ready.
Downloading...
Error in tryCatchList(expr, classes, parentenv, handlers) : 
  Could not find metadata file.
Calls: download -> tryCatch -> tryCatchList
Execution halted
`

**Comment by Wytamma** [comment]
Hi 👋  what version are you using? Can you try updating GISAIDR. I’m pretty sure this was fixed in bb7f8483393c0695c092256d05becbb320252a45

**Comment by gk7279** [comment]
I was using the latest version and it didn't work. I opted other tools. Thanks. Closing now.
