### ISSUE TITLE
login function not working in v0.7.4

### ISSUE THREAD

**Issue by ai4pharma** [Wytamma/GISAIDR#19]
I just updated the package from v0.7.0 and v0.7.4 and got following error message from login function.
**Error in matches[[1]][[2]] : subscript out of bounds**
Debug shows the error is due to
**extract_first_match("div class=\"sys-datatable\" id=\"(.*)_table", customSearch_page_text)**
It seems that customSearch_page_text doesn't include datatable instead of following error messages.
**alert(' The session has expired. The application will be restarted!');**
However, the login function works weel when I switched the database to EpiRSV.

**Comment by Wytamma** [comment]
Hey @ai4pharma, yeah it seems like something is breaking with the session token... It looks like something on GISAID's end has changed, but it's not obvious to me what that is. I'll keep looking into it today and let you know how I go.

**Comment by Wytamma** [comment]
It seems that the 'Custom Selection' panel that we used for downloading the now results in an expired session. Idk if that's a bug in GISAID or their way of depreciating this feature,  but it might be time to swap to the search panel (which is what the EpiRSV login uses) referenced here https://github.com/Wytamma/GISAIDR/issues/1#issuecomment-1065286119

**Comment by Wytamma** [comment]
Solved in [c90e4fd](https://github.com/Wytamma/GISAIDR/commit/c90e4fd98f304371ebb5fea5be31d0e14ebfba0b)
