### ISSUE TITLE
Failed to query info when the target infos is > 100000

### ISSUE THREAD

**Issue by XINBADA426** [Wytamma/GISAIDR#20]
```R
# OK
df <- query(
  credentials = credentials,
  from_subm = "2022-04-01",
  to_subm = "2022-04-30",
  complete = T,
  high_coverage = T,
  low_coverage_excl = T,
  start_index = 99000,
  nrows = 1000
)
# Returning 99000-1e+05 of 122207 entries.
```
```R
df <- query(
  credentials = credentials,
  from_subm = "2022-04-01",
  to_subm = "2022-04-30",
  complete = T,
  high_coverage = T,
  low_coverage_excl = T,
  start_index = 99000,
  nrows = 2000
)
# Returning 99000-99000 of 0 entries.
```

**Comment by Wytamma** [comment]
Hi @XINBADA426,  Hmm weird bug... for me the second works for me kinda... there's definitely something going wrong with the nrows argument! I'll look into this. Thanks for the report.

**Comment by Wytamma** [comment]
I’ve looked into this ad it appears to be a GISAID issue i.e. they don’t even let you page past 100000 samples on their site :/ nothing I can really do about this. I’d suggest narrowing your search e.g. download one lineage at a time?
