### ISSUE TITLE
Could not login into GISAID database

### ISSUE THREAD

**Issue by kusonahikari** [Wytamma/GISAIDR#22]
Previously, I could login into EpiCoV database via code below
`library(GISAIDR)
username <- charToRaw(getPass::getPass(msg = "GISAID username:"))
password <- charToRaw(getPass::getPass(msg = "GISAID password:"))
credentials <- login(username = rawToChar(username), password = rawToChar(password), database="EpiRSV")
`
However, I used the same code again and encoutered this error 
`Error in parseResponse(response) : Error! Please login again.
In addition: Warning message:
In parseResponse(response) :
  There was an error please see: https://github.com/Wytamma/GISAIDR/issues/1`

My GISAIDR version is `0.7.6` with R `4.1.2`

**Comment by Wytamma** [comment]
Did you try logging in without using the RSV database? 

credentials <- login(username = rawToChar(username), password = rawToChar(password))

**Comment by Wytamma** [comment]
Hi @kusonahikari, I've fixed the login bug in 0.7.7. I'll close this issue now, but please let me know if it doesn't work for you.

**Comment by kusonahikari** [comment]
Thank @Wytamma. The code works fine for EpiRSV. However, when I specified the database as EpiCov, there' stil this error. 
`Error in parseResponse(response) : Internal server Error.
In addition: Warning message:
In parseResponse(response) :
  An internal server error occurred. Please report this incident including the following error-details:<p><b>error-token: 5AW57</b>`

**Comment by Wytamma** [comment]
Hey @kusonahikari  That looks like a different error to the one you initially posted so I've created a new issue (#23)
