### ISSUE TITLE
EpiCoV login error

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/GISAIDR#23]
Thank @Wytamma. The code works fine for EpiRSV. However, when I specified the database as EpiCov, there' stil this error. 
`Error in parseResponse(response) : Internal server Error.
In addition: Warning message:
In parseResponse(response) :
  An internal server error occurred. Please report this incident including the following error-details:<p><b>error-token: 5AW57</b>`

_Originally posted by @kusonahikari in https://github.com/Wytamma/GISAIDR/issues/22#issuecomment-1146783536_

**Comment by Wytamma** [comment]
Hey @kusonahikari can you try running the following code and trying to login again?

```
detach("package:GISAIDR", unload=TRUE)
devtools::install_github("Wytamma/GISAIDR")
Sys.setenv(GISAIDR_DEBUG=1)
```

**Comment by kusonahikari** [comment]
Thank @Wytamma alot , It works fine now.

**Comment by Wytamma** [comment]
>
