### ISSUE TITLE
Only return 50 rows

### ISSUE THREAD

**Issue by lujing-jlu** [Wytamma/GISAIDR#24]
df_alpha <- query(credentials = credentials, variant = GISAIDR::Variants$alpha, from_subm = '2022-04-08', to_subm = '2022-06-08', load_all = TRUE)
Loading all 3492 entries...
Returning 0-50 of 3492 entries.

**Comment by lujing-jlu** [comment]
I use for loop to download them.
`variants = c("delta","lambda","mu","epsilon","omicron")#"alpha", "beta", "gamma",
for (variant in variants){
  credentials <- login(username = username, password = password)
  total_df <- query(credentials = credentials, variant = GISAIDR::Variants[variant][[1]], from_subm = '2022-04-08', to_subm = '2022-06-08', total=T)
  nodes = seq(0,total_df+50,50)
  df <- data.frame(stringsAsFactors=FALSE)
  for(i in 1:length(nodes)-1){
    df_i <- query(credentials = credentials, variant = GISAIDR::Variants[variant][[1]], from_subm = '2022-04-08', to_subm = '2022-06-08',start_index = nodes[i],nrows =50)
    df <- rbind(df, df_i)
  }
  list_of_accession_ids <- df$accession_id
  full_df <- download(credentials = credentials, list_of_accession_ids = list_of_accession_ids, get_sequence=TRUE)
  write.csv(full_df, paste0("full_df_",variant,".csv"),row.names=FALSE)
  export_fasta(full_df, out_file_name = paste0("GISAID_",variant,"_sequences.fasta"))
}

`

**Comment by Wytamma** [comment]
Thanks @lujing-jlu! I’ll see if I can add something like this loop into the library to make it a bit easier

**Comment by lujing-jlu** [comment]
I tried to use parallel multithreading to do this, now my account was punished.

**Comment by Wytamma** [comment]
Fixed in e4b2d6d5cb04f10f2400bc669a0f892cb580390e
