### ISSUE TITLE
Can data be downloaded more than 5000 sequences at a time  ?

### ISSUE THREAD

**Issue by josenikhid97** [Wytamma/GISAIDR#25]
Hello 

# username <- Sys.getenv(''username")
# password <- Sys.getenv("password")

1) The above commands are not saving the information(do i need to install extra library or packages, other than devtools and GISAIDR).

2) Can i download more than 5000 sequences at a time ? please suggest me because i am trying to download all the sequences from starting of pandemic to now, or best possible way to do that job 

3) If i am trying to download atleast some sequences less than 5000, it shows me  GISAIDR masking package:utils like timesatmp and also there was also problem with the lubridate package masking date, intersect, setdiff, union  

4) if i am downloading sequences, there is also another problem of login entries which shows that the login details are expired and i have to login again (this shows at the middle of sequences downloading "execution halted", so i have to start again downloading and shows the same error as a repeat process.

Eagerly waiting for your response ,

Thank you in advance

**Comment by Wytamma** [comment]
Hi @josenikhid97, 

Thanks for the questions! 

1. `Sys.getenv` just gets environment variables. If you don't have your password/username set as environment variables you can hard code them e.g.
```
credentials <- login(username = '<your GISAID username here>', password = '<your GISAID password here>')
```
2. No you can't download more than 5000 sequences at a time. This is a limit set by GISAID. You could always just batch the downloads to get around this.

3. Just use `GISAIDR` without importing it i.e. don't call library(GISAIDR), just use `GISAIDR::login(...)`,  `GISAIDR::query(...)`, etc.

4. I don't have any control over GISAID, if it's taking a long time to download and your session expires you need to just batch things into smaller groups to download. 

You probably shouldn’t use `GISAIDR` to download all of GISAID. I highly doubt it'll work without a lot of effort and will take a very long time. You should probably figure out why exactly you want the genomes and make a specific query so you don't have to download as much.

**Comment by josenikhid97** [comment]
Hello @Wytamma,

Thank you for the answers :+1: 

Every thing works fine now.

Thank you for this amazing tool and for your easily understandable  documentation. :+1:
