### ISSUE TITLE
Support for searching by AA substitutions?

### ISSUE THREAD

**Issue by tomwenseleers** [Wytamma/GISAIDR#28]
Would it also be possible to support searching by AA substitutions?
E.g. I would like to be able to search for E_T11A,NSP3_S403L (picks up more BA.2.75 than searching by lineage) in the Substitutions field with submission date between 2022-07-26 and 2022-07-30. Could that also be supported?

**Comment by Wytamma** [comment]
Solved in https://github.com/Wytamma/GISAIDR/pull/39
