### ISSUE TITLE
bug: "internal server error" with download()

### ISSUE THREAD

**Issue by brianhigh** [Wytamma/GISAIDR#30]
This used to work fine a week or so ago, but something changed, perhaps with GISAID's API... and so now download() doesn't work anymore.

# Example:

credentials <- login(username = username, password = password)
df_ids <- query(credentials, location = "Wuhan", from = "2020-01-05", to = "2020-01-05")
ids <- df_ids$accession_id
ids
##[1] "EPI_ISL_406801"

df_seqs <- download(credentials, ids)

##Selecting entries...
##Compressing data. Please wait...
##Error in parseResponse(res) : Internal server Error.
##In addition: Warning message:
##In parseResponse(res) :
## An internal server error occurred. Please report this incident including the following error-details:<p><b>error-token: NCW96</b>

traceback()

##3: stop("Internal server Error.")
##2: parseResponse(res)
##1: download(credentials = credentials, list_of_accession_ids = ids, 
       get_sequence = TRUE)

# Which appears to come from this section of download():

message("Compressing data. Please wait...")
res <- httr::POST(GISAID_URL, httr::add_headers(.headers = headers), 
                  body = data)
j <- parseResponse(res)

**Comment by Wytamma** [comment]
Thanks for the report @brianhigh! I’ll look into this today.

**Comment by Wytamma** [comment]
Ah okay so GISAID has added a terms and conditions pop up that your have to accept before downloading sequences.

**Comment by brianhigh** [comment]
Can download() be modified to handle that transaction, and automated with a parameter like accept_terms=TRUE?

**Comment by tomwenseleers** [comment]
Yes, had to adapt my RSelenium code as well to deal with this - you can check out here how I got around that: [https://stackoverflow.com/questions/72632118/download-covid-patient-metadata-from-gisaid-website-in-r-using-rselenium](https://stackoverflow.com/questions/72632118/download-covid-patient-metadata-from-gisaid-website-in-r-using-rselenium)

**Comment by Wytamma** [comment]
Thanks @tomwenseleers! Sorry for the delay @brianhigh, I've been traveling. It's now fixed in v0.9.3.
