### ISSUE TITLE
virus_name argument for query() and/or download() functions

### ISSUE THREAD

**Issue by gdonovan1** [Wytamma/GISAIDR#32]
I have a list of sequences from a separate database for which I have variables equivalent to virus_name but not accession_id. I would like to download the metadata using this virus_name list. would it be possible to create a list_of_virus_names argument under the download() function, and/or a similar option under the query() function?

**Comment by Wytamma** [comment]
Hi @gdonovan1, I added virus_name to `query` in https://github.com/Wytamma/GISAIDR/commit/ea5eef66291aaf6bea866cf23978ad25bb573a35 :)

**Comment by gdonovan1** [comment]
Thanks so much! It seems GISAID itself is limited to one search item per parameter. Have you ever found a way around this?

**Comment by Wytamma** [comment]
Hey @gdonovan1! 

Yeah it seems just using a list works 😅

```R
virus_names <- list("hCoV-19/Ireland/KY-Enfer-230922004_A4/2022", "hCoV-19/Ireland/CO-Enfer-240922010_E9/2022")
df <- query(credentials = credentials, virus_name=virus_names)
```
Returning 0-2 of 2 entries.
```
df$virus_name
```
[1] "hCoV-19/Ireland/CO-Enfer-240922010_E9/2022" "hCoV-19/Ireland/KY-Enfer-230922004_A4/2022"

**Comment by gdonovan1** [comment]
This is so great! Thanks, I’ll try that out.

**Comment by gdonovan1** [comment]
It seems that something is off. I’m not getting the same result:
***@***.***

I’ve updated to v0.9.4 but anything I include in the virus_name argument is returning the full data.

**Comment by Wytamma** [comment]
Hmm can you please make sure you've detached the old version i.e. run `detach("package:GISAIDR", unload=TRUE)` then update? It's defiantly working for me...  but there are cases where people have different levels of access to GISAID, lets hope this is not one. 

```
> credentials <- login(username = username, password = password)
> virus_names <- list("hCoV-19/Ireland/KY-Enfer-230922004_A4/2022", "hCoV-19/Ireland/CO-Enfer-240922010_E9/2022"
> df <- query(credentials = credentials, virus_name=virus_names)
Returning 0-2 of 2 entries.
> df$virus_name
[1] "hCoV-19/Ireland/CO-Enfer-240922010_E9/2022" "hCoV-19/Ireland/KY-Enfer-230922004_A4/2022"
```

**Comment by gdonovan1** [comment]
I managed to get it to work. One final issue in the way is that querying a list in the virus_name argument appears to be limited to a small number of records. For example, where virus_names is a large list of

**Comment by Wytamma** [comment]
No idea 😆 it's just classic GISAID to have some undocumented feature that does something unexpected. Maybe you'll just have to limit yourself to small batches?

**Comment by gdonovan1** [comment]
I was able to get it set up to work with smaller queries in chunks of 50. This helps to cut back on how often I have to download manually, so thanks so much!
