### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Danish-1311** [Wytamma/GISAIDR#38]
Error in parseResponse(response) : Username or password wrong!
I always get this error when i enter my username and password but when i login in GISAID EpiCov, it is working fine.
Here is my current code:
library(GISAIDR)
username = Sys.getenv("")
password = Sys.getenv("")
login(username = username, password = password)

**Comment by Wytamma** [comment]
Hi @Danish-1311! I'm assuming that you're not using `Sys.getenv("")` for your password and username as that wouldn't work. Can you confirm that you're passing the correct username and password? e.g. hard code it.
