### ISSUE TITLE
Difference between `load_all` and `total` arguments within `query` function

### ISSUE THREAD

**Issue by BryanTegomoh** [Wytamma/GISAIDR#40]
Great work putting this together. 

What's the purpose of the `total` argument in the query function? 

Have you considered an option for a load_all within the download(). Looks like download is limited to only 50 sequences?

**Comment by Wytamma** [comment]
Hey @BryanTegomoh,

The total argument returns the total number of entries that match a query this is useful for getting the number without having to page through all the results. 

Query is limited to 50 results (by gisaid) unless you use the fast argument. The download limit is variable per user (by gisaid) for example I can download 5000 entries however others report more or less. You could figure out your limit then batch the results of a fast query to download say 1000 entries at a time, thus imitating load_all. 

There’s an open issue the has some more details #29

**Comment by BryanTegomoh** [comment]
Makes sense. I can manually curate as many sequences from GISAID. And `query()` doesn't give me a limit. Just tested this and was able to query over 14,000 entries. However, `download()` limits me to 50. Wondering if a `load_all()` would fix this per users' query limit. I agree the download in chunks mentioned in #29 might be temporary fix.

**Comment by Wytamma** [comment]
Query batches entries into groups of 50 internally to get around the 50 limit. Could do the same for download but it should work for move than 50 ids. Can you provide the code you’re using? It’s possible that gisaid now limits the number of downloads to 50 (but I doubt that’s true because it would make their site unusable).

**Comment by BryanTegomoh** [comment]
Here's a snippet of the code: 

credentials <- GISAIDR::login(username = "USERNAME", password = "PASSWORD", database = "EpiCoV")

#Dates for query
six_weeks_ago <- as.character(floor_date(as.Date(Sys.Date() - 42), "week")) #set to last Sunday prior to sample date
todays_date <- as.character(as.Date(Sys.Date()))  

# Generating a list of accession ids of interest
list_of_accession_ids <- query(credentials = credentials, 
                                               location = "Nebraska", 
                                               from = six_weeks_ago,
                                               to = todays_date,
                               load_all = TRUE, 
                               total = F
                               ) %>% pull(accession_id)

# Downloading data
genomic_data <- download(credentials = credentials, 
                                 list_of_accession_ids = list_of_accession_ids , 
                                 get_sequence = TRUE, 
                                 clean_up = FALSE 
                                  )  

# Output `genomic_data` = 50 sequences ( != expected output ) 


Expectation is over 50 observations in this example

**Comment by Wytamma** [comment]
The following works for me... Maybe there's an error with your date query?
```
library(GISAIDR)
library(tidyverse)
username = Sys.getenv("GISAIDR_USERNAME")
password = Sys.getenv("GISAIDR_PASSWORD")
credentials <- login(username = username, password = password)
```
```
list_of_accession_ids <- query(credentials = credentials, 
                               location = "Nebraska", 
                               from = "2023-01-17",
                               fast = TRUE
) %>% pull(accession_id)
```
```
genomic_data <- download(credentials = credentials, 
                         list_of_accession_ids = list_of_accession_ids , 
                         get_sequence = TRUE
)  
nrow(genomic_data)
```
[1] 266

**Comment by BryanTegomoh** [comment]
Thank you @Wytamma. The extra arguments were taken out and it works as expected. It's unclear why the extra arguments caused the issue, but I suspect that it may have been related to how the function was interpreting the input. In any case, I was able to overcome the issue and make the workflow more reproducible by dynamically setting the query dates and converting them to character strings.
