### ISSUE TITLE
tar: Removing leading `/' from member name

### ISSUE THREAD

**Issue by NiklausMikaelson12138** [Wytamma/GISAIDR#44]
tar: Removing leading `/' from member name
 how can i solve this problem?

**Comment by Wytamma** [comment]
Hi @NiklausMikaelson12138 is there an associated error? I think this is just a warning from tar and the download should still work?

**Comment by NiklausMikaelson12138** [comment]
Hi, It did not go well. The script justed stopped while giving this error.

**Comment by NiklausMikaelson12138** [comment]
> Hi @NiklausMikaelson12138 is there an associated error? I think this is just a warning from tar and the download should still work?
Hi, It did not go well. The script justed stopped while giving this error.

**Comment by Wytamma** [comment]
Sorry to hear that! Can you provide the script?

**Comment by NiklausMikaelson12138** [comment]
this script is like this
credentials = login(username = '*',password = '*')
df <- query(credentials = credentials,lineage = 'BA.2',complete = TRUE,high_coverage = TRUE,location="North America / USA / New York",fast = TRUE)
id = df$accession_id
full_df_with_seq <- download(credentials = credentials,list_of_accession_ids = id,get_sequence = TRUE)
export_fasta(full_df_with_seq,out_file_name = paste0('C:\\Users\\acer\\Desktop\\','omicron','.fasta'),export_dated_only = F)

> Sorry to hear that! Can you provide the script or the full traceback?

**Comment by Wytamma** [comment]
Can you try to adding `print(head(full_df_with_seq))` after this line `full_df_with_seq <- ...` to confirm the download worked?

**Comment by NiklausMikaelson12138** [comment]
I will try it and reply later

**Comment by Wytamma** [comment]
You can also add `Sys.setenv(GISAIDR_DEBUG = 1 )` to the top of the file to turn on debug mode.

**Comment by Wytamma** [comment]
hmm it might be an issue with the GISAID sever hence `Error in send_request(method = "POST", data = data) : Server error!`. 

4593 is a lot of entries to download. You might need to break them up into serval smaller batches. Maybe just try downloading `10` entries first to confirm this works 

```R
full_df_with_seq <- download(credentials = credentials,list_of_accession_ids = id[1:10], get_sequence = TRUE)
```

**Comment by NiklausMikaelson12138** [comment]
ok, maybe it's too large ,I will try,  thank you!

**Comment by NiklausMikaelson12138** [comment]
Thank you for your kind help. Changing the entries small solves the problem. Thank you again. Wish you best!
