### ISSUE TITLE
Is it possible to change the sequence header format

### ISSUE THREAD

**Issue by dawnmy** [Wytamma/GISAIDR#45]
Thank you for developing this useful tool for dealing with GISAID data. It seems, by default `export_fasta` generates fasta file with sequence header `<country>|<lineage>|<accession>|<submission date>`. Is it possible to customize the header format, for example, `<accession> <country>|<lineage>|<collection date>`? I would like to use accession to select and split the fasta file later based on the accession IDs.

**Comment by Wytamma** [comment]
Hi @dawnmy!

**Comment by Wytamma** [comment]
I've added the the option to choose which columns are include in the export using the `columns` argument (cb8da27).

```R
export_fasta(df, file, columns = c("accession_id", "country", "pangolin_lineage", "date"))
```

You could also construct your own header 

```R
df$header <- paste(df$accession_id, df$country)
export_fasta(df, file, columns = c("header")
```
