### ISSUE TITLE
Error while downloading sequence for USA

### ISSUE THREAD

**Issue by dawnmy** [Wytamma/GISAIDR#48]
Thank you for developing such a convenient tool. I am using GISAIDR to download SARS-Cov-2 sequences for each country based on the `Accession ID` in the sequence metadata file from GISAID.  It fails sometimes. The error message:

```
Data ready.
Error in send_request(method = "POST", data = data) : Server error!
Calls: download -> send_request
In addition: Warning message:
In send_request(method = "POST", data = data) :
  An error occurred while trying to POST https://www.epicov.org/epi3/frontend?
Execution halted
```
I repeated several times and got the same error, so it is unlikely a temporary connection error. It might because there is an invalid `accession ID` . If so, is there a way to skip the invalid IDs during query and download?

**Comment by Wytamma** [comment]
Hey @dawnmy! 

Can you provide an example of the `accession ID`s that are producing this error?

You can also try truing on debug mode with `Sys.setenv(GISAIDR_DEBUG = 1)` to get a bit more info.

**Comment by Wytamma** [comment]
Yeah it seems that GISAID sets different download limits for different people and there’s no way to tell what the limit is without testing what you can download 🤷‍♀️ glad it’s working now. Please reopen this issue if you run into other problems.
