### ISSUE TITLE
Download amino acid sequences for specified protein

### ISSUE THREAD

**Issue by dawnmy** [Wytamma/GISAIDR#49]
Is it possible to download sequences of specified protein (e.g. spike protein) of SARS-Cov-2 based on accession IDs using GISAIDR?

**Comment by Wytamma** [comment]
Hi @dawnmy is this something that's possible to do though [https://www.epicov.org/](https://www.epicov.org)? Currently it's not possible wth GISAIDR and I'm not clear as to how it's done on the website?

**Comment by dawnmy** [comment]
On the website, it seems we can only download all the amino sequences in a compressed file.
