### ISSUE TITLE
Feature Requests: Location, Submitted Date etc

### ISSUE THREAD

**Issue by gk7279** [Wytamma/GISAIDR#7]
Thanks for the wonderful tool.

Can you make a manual of the options involved, please?

In addition to the country like USA, can we ask for specific location say Illinois/Chicago?

Can we filter using submitted_date with both query and download options?

Thanks.

**Comment by Wytamma** [comment]
Hi and thanks for your interest. 

I've added list of GISAID locations (to "state" level) that can be queried in [GISAID_LOCATIONS.txt](https://github.com/Wytamma/GISAIDR/blob/master/GISAID_LOCATIONS.txt). The location search is hierarchical e.g. querying for 'Africa / ...' will return all the regions within Africa, while querying for 'Africa / Angola / ...' will only return the regions in Angola. Region can be further subdivided by specifying more levels e.g. 'North America / USA / Alabama / Butler County'.

Currently the date (to, from) filter is only for collection date (`collection_date` is more relevant for biological contexts). I will add `submitted_date` filtering to the list of improvements. 

The download function requires a list of IDs. To filter using `submitted_date` in download just filter your IDs e.g. 
```
df <- query(credentials = credentials, lineage = 'W.1', load_all = TRUE)
filtered_df <- df[as.Date(df$submission_date) == as.Date('2021-02-17'), ]
filtered_full_df <- download(credentials, filtered_df$accession_id)
```
