### ISSUE TITLE
Please add "complete" "high coverage" and "collection date compl" to query

### ISSUE THREAD

**Issue by sebastianduchene** [Wytamma/GISAIDR#8]
I noticed that some of the sequences we are getting have long stretches of N's that are not flagged in the metadata, but which can be excluded on the website by ticking a few boxes. Is it easy to add these to query?
"complete" "high coverage" and "collection date compl" to query

**Comment by Wytamma** [comment]
I've added the `complete` feature and will add the others shortly. I also wrote up a short developer guide: https://github.com/Wytamma/GISAIDR#dev-guide.

**Comment by Wytamma** [comment]
Solved in 2cbeb03b6d15403f96a3a85be29a0c0745e2e3b8
